name: MobileGlues

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Set Up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c
          local-cache: true
          link-to-sdk: true

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build apk
        run: ./gradlew assembleRelease --info

      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.repository_name }}_${{ env.date_today }}_${{ github.sha }}
          path: app/build/outputs/apk/release/
